create table if not exists users(
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    surname varchar(255) not null,
    birth_date date not null,
    email varchar(255) unique not null
);


create table if not exists card_info(
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    number varchar(255) unique not null,
    holder varchar(255) not null,
    expiration_date date not null,
    foreign key (user_id) references users(id) on delete cascade
);