create table if not exists items (
                       id bigint generated by default as identity primary key,
                       name varchar(255) not null unique,
                       price decimal(10,2) not null
);

create table if not exists orders (
                        id bigint generated by default as identity primary key,
                        user_id bigint not null,
                        status varchar(50) not null,
                        creation_date timestamp not null
);

create table if not exists order_items (
                             id bigint generated by default as identity primary key,
                             order_id bigint not null,
                             item_id bigint not null,
                             quantity int not null,

                             constraint fk_order_items_orders
                                 foreign key (order_id)
                                     references orders (id)
                                     on delete cascade,

                             constraint fk_order_items_items
                                 foreign key (item_id)
                                     references items (id)
                                     on delete restrict
);
